# Generated by Django 3.1.4 on 2021-02-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
    ]
