# Generated by Django 3.1.4 on 2021-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210225_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
