# Generated by Django 3.1.6 on 2021-02-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210225_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('mobileno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryAdvertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.advertiser')),
                ('Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.industry')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
