# Generated by Django 3.1.6 on 2021-02-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210301_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryadvertiser',
            old_name='Advertiser',
            new_name='advertiser',
        ),
        migrations.RenameField(
            model_name='industryadvertiser',
            old_name='Industry',
            new_name='industry',
        ),
    ]
